import { useEffect, useState } from "react";
import { Check, CheckCircle2, Clock3, Eye, RefreshCw, XCircle } from "lucide-react";
import { api } from "../api";
import Header from "../components/Header";
import AppFooter from "../components/AppFooter";
import "./ApprovalPage.css";

const rows = [
  ["Month Plan","monthPlan","target"],["Month Actual","monthActual"],["Production Plan","productionPlan","target"],["Production Actual","productionActual"],["UPH Target","uphTarget","target"],["UPH Actual","uphActual"],
  ["UPPH Installed","upphInstalled","target"],["UPPH Actual","upphActual"],
  ["CPH Target","cphTarget","target"],["CPH Actual","cphActual"],
  ["FPY Actual","fpyActual"],["FTY Actual","ftyActual"],["RTY Actual","rtyActual"],
  ["OS&D — Reporting Date","osdReportingDateValue"],["OS&D — Reporting Date %","osdReportingDatePercent"],["OS&D — MTD","osdMtdValue"],["OS&D — MTD %","osdMtdPercent"],
  ["Planned OT (Hrs)","plannedOTManhours"],["Unplanned OT (Hrs)","unplannedOTManhours"],["Actual OT (Hrs)","actualOTManhours"],["Open WO (Qty)","openWOQty"],["> 7 Days WO (Qty)","over7DaysWOBalanceQty"],
  ["TRC In (Qty)","dailyTRCInQty"],["TRC Out (Qty)","dailyTRCOutQty"],["Failure Inflow (%)","trcOverallFailureInflowPercent"],["TRC > 3 Days (Cr)","trcLyingOver3DaysCr"],
];

export default function ApprovalPage({ session, onSignOut }) {
  const [pending,setPending]=useState([]); const [history,setHistory]=useState([]); const [selected,setSelected]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [comment,setComment]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const [p,h]=await Promise.all([api.get("/approvals/pending"),api.get("/approvals/history")]);setPending(p||[]);setHistory(h||[]);if(selected){const found=(p||[]).find(x=>x.approvalQueueId===selected.approvalQueueId);if(found) setSelected(found); else setSelected(null);}}catch(e){setError(e.message)}finally{setLoading(false)}};
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void load();},[]);
  const open=async(item)=>{setError("");try{setSelected(await api.get(`/approvals/${item.approvalQueueId}`));setComment("")}catch(e){setError(e.message)}};
  const review=async(approve)=>{if(!selected)return;if(!approve&&!comment.trim()){setError("Please add a rejection comment before sending it back.");return}setBusy(true);setError("");try{if(approve)await api.post(`/approvals/${selected.approvalQueueId}/approve`,{});else await api.post(`/approvals/${selected.approvalQueueId}/reject`,{comment});setSelected(null);setComment("");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="approval-page"><Header user={session.user} onSignOut={onSignOut}/><main className="approval-content"><header className="approval-hero"><div><span>APPROVAL WORKSPACE</span><h1>Daily report approvals</h1><p>Review only the brands assigned to you. Approved reports are locked for the dashboard; rejected reports return to the contributor with your comment.</p></div><button className="approval-refresh" onClick={load}><RefreshCw size={15}/> Refresh</button></header>{error&&<div className="approval-error">{error}</div>}<section className="approval-stats"><div><Clock3/><span>Pending</span><strong>{pending.length}</strong></div><div><CheckCircle2/><span>Reviewed</span><strong>{history.length}</strong></div></section><div className="approval-layout"><section className="approval-queue panel"><div className="panel-head"><div><span>PENDING QUEUE</span><h2>Reports waiting for you</h2></div></div>{loading?<div className="approval-empty">Loading approval queue…</div>:!pending.length?<div className="approval-empty"><CheckCircle2 size={25}/><strong>Queue is clear</strong><span>No pending reports for your assigned brands.</span></div>:<div className="approval-list">{pending.map(item=><button className={`approval-row ${selected?.approvalQueueId===item.approvalQueueId?"selected":""}`} key={item.approvalQueueId} onClick={()=>open(item)}><div className="approval-row-date">{formatDate(item.submittedAt)}</div><div className="approval-row-main"><strong>{item.customerName} · {item.categoryName}</strong><span>{item.lineName}{item.modelName?` · ${item.modelName}`:""} · {item.submittedBy}</span></div><span className="pending-pill">Pending</span><Eye size={15}/></button>)}</div>}</section><section className="approval-detail panel">{selected?<Detail item={selected} comment={comment} setComment={setComment} busy={busy} onApprove={()=>review(true)} onReject={()=>review(false)}/>:<div className="approval-empty detail-empty"><Eye size={28}/><strong>Select a report</strong><span>Choose a pending submission to inspect the KPI values and decide whether to approve or reject it.</span></div>}</section></div><section className="panel approval-history"><div className="panel-head"><div><span>RECENT REVIEW HISTORY</span><h2>Previously handled reports</h2></div></div>{history.slice(0,8).map(item=><div className="history-row" key={item.approvalQueueId}><div><strong>{item.customerName} · {item.categoryName}</strong><span>{item.lineName}{item.modelName?` · ${item.modelName}`:""}</span></div><span className={`history-status ${item.status.toLowerCase()}`}>{item.status}</span><small>{item.comments||item.reviewer||"—"}</small></div>)}</section></main><AppFooter/></div>;
}
function Detail({item,comment,setComment,busy,onApprove,onReject}){const isSmt=item.categoryName?.trim().toUpperCase()==="SMT";const visibleRows=rows.filter(([,key])=>isSmt?key!=="upphInstalled"&&key!=="upphActual":key!=="cphTarget"&&key!=="cphActual");return <div className="detail-inner"><div className="detail-title"><div><span>{item.customerName} · {item.categoryName}</span><h2>{item.lineName} · {item.modelName||"Model"}</h2><p>Submitted by {item.submittedBy} · {formatDate(item.submittedAt)}</p></div><span className="pending-pill">Pending verification</span></div><div className="detail-plan-box"><div><span>MONTHLY PLAN REFERENCE</span><strong>Administrator KPI configuration</strong></div><div className="plan-reference-grid">{[["Production Plan","productionPlan"],["UPH Target","uphTarget"],["UPPH Target","upphTarget"],["CPH Target","cphTarget"],["FPY Target","fpyTarget"],["FTY Target","ftyTarget"],["RTY Target","rtyTarget"],["OS&D Target","osdTarget"],["OT Target","otTarget"]].map(([label,key])=><div key={key}><small>{label}</small><b>{formatValue(item.metrics?.plan?.[key],key)}</b></div>)}</div></div><div className="detail-metrics">{visibleRows.map(([label,key,type])=><div className="detail-metric" key={key}><span>{label}</span><strong className={type==="target"?"target":item.metrics?.[key]===null?"empty":""}>{formatValue(item.metrics?.[key],key)}</strong></div>)}</div><div className="detail-issue"><span>ISSUE DESCRIPTION</span><p>{item.metrics?.issueDescription||"No issue description provided."}</p></div><div className="review-box"><label>Rejection comment <small>required only when rejecting</small><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Tell the contributor what needs to be corrected…" rows={3}/></label><div className="review-actions"><button className="reject" disabled={busy} onClick={onReject}><XCircle size={16}/> Reject & return</button><button className="approve" disabled={busy} onClick={onApprove}><Check size={16}/> Approve & lock</button></div></div></div>}
function formatValue(v,key){if(v===null||v===undefined||v==="")return"—";const n=Number(v);if(!Number.isFinite(n))return v;const pct=/Percent|fpy|fty|rty/i.test(key);return pct&&n>0&&n<1?`${(n*100).toFixed(2)}%`:n.toLocaleString("en-IN",{maximumFractionDigits:2})}
function formatDate(v){return new Date(v).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}
