import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Search, RefreshCw } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api";
import Header from "../components/Header";
import AppFooter from "../components/AppFooter";
import "./ApprovalHistory.css";
export default function ApprovalHistory({session,onSignOut}){const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[error,setError]=useState("");const load=()=>api.get("/approvals/history").then(setRows).catch(e=>setError(e.message));
useEffect(load,[]);const filtered=useMemo(()=>rows.filter(x=>`${x.customerName} ${x.categoryName} ${x.lineName} ${x.modelName||""}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);return <div className="approval-history-page"><Header user={session.user} onSignOut={onSignOut}/><main className="ah-main"><div className="ah-head"><div><span>APPROVAL HISTORY</span><h1>Reviewed reports</h1><p>Previously approved and rejected submissions for your assigned brands.</p></div><button onClick={load}><RefreshCw size={15}/> Refresh</button></div><div className="ah-toolbar"><div><Search size={16}/><input placeholder="Search customer, line or model" value={search} onChange={e=>setSearch(e.target.value)}/></div><Link to="/approvals"><ArrowLeft size={14}/> Back to queue</Link></div>{error&&<div className="ah-error">{error}</div>}<section className="ah-table-wrap"><table><thead><tr><th>Report</th><th>Line / model</th><th>Submitted</th><th>Reviewed</th><th>Status</th><th>Reviewer / comment</th></tr></thead><tbody>{filtered.map(x=><tr key={x.approvalQueueId}><td><strong>{x.customerName}</strong><small>{x.categoryName}</small></td><td><strong>{x.lineName}</strong><small>{x.modelName||"—"}</small></td><td>{format(x.submittedAt)}</td><td>{x.reviewedAt?format(x.reviewedAt):"—"}</td><td><span className={`ah-status ${x.status.toLowerCase()}`}>{x.status}</span></td><td><strong>{x.reviewer||"—"}</strong><small>{x.comments||"No comment"}</small></td></tr>)}{!filtered.length&&<tr><td colSpan="6" className="ah-empty">No reviewed reports found.</td></tr>}</tbody></table></section></main><AppFooter/></div>}
function format(v){return new Date(v).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}
